---
title: "Assignment 1"
author: "Ted Ladas - s2124289"
date: "27/02/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library(MARSS)
library(rjags)
require(fBasics)
library(INLA)
```

```{r 1b}
data(graywhales)
# print(graywhales)
missing.data <- matrix(data=c(1986,1988,1989,1990,1991,1994,1996,NA,NA,NA,NA,NA,NA,NA), ncol=2, byrow=FALSE)
graywhales <- as.matrix(rbind(graywhales, missing.data))
graywhales <- graywhales[order(graywhales[,1]),]

model0 = "model{
  x.0  ~ dnorm(log(2500), 1)
  x[1] ~ dnorm(beta * x.0 + u, inv.sigma02)
  y[1] ~ dnorm(x[1], inv.ita02)
  
  for (t in 2:n){
     mu[t] = beta*x[t-1] + u
     x[t] ~ dnorm(mu[t], inv.sigma02)
     y[t] ~ dnorm(x[t], inv.ita02)
  } 
  
  beta ~ dunif(0,1)
  u ~ dexp(1)
  inv.sigma02 ~ dgamma(0.1,0.1)
  inv.ita02 ~ dgamma(0.1,0.1)
  sigma2 = 1/inv.sigma02
  ita2 = 1/inv.ita02
}"

n=dim(graywhales)[1]
coef = c('beta','u','sigma2','ita2')
burn.in = 2*1e3
jm0 = jags.model(textConnection(model0), data=list(n=n, y=log(graywhales[,2])), n.chains=3)
update(jm0, burn.in, progress.bar='none')
res = coda.samples(jm0, variable.names=coef, n.iter=5e3, thin=500)
```

```{r 1c}
gelman.diag(res)
round(effectiveSize(res),2)
par(mfrow=c(2,2))
acf(res[[1]][,"beta"])
acf(res[[1]][,"u"])
acf(res[[1]][,"sigma2"])
acf(res[[1]][,"ita2"])
```

```{r 1d}
summary(res)
plot(res)
beta.den = res[[1]][,1]
ita2.den = res[[1]][,2]
sigma2.den = res[[1]][,3]
u.den = res[[1]][,4]
#par(mfrow=c(2,2))
x = seq(0,1,by=0.001)
y = dunif(x, min=0, max=1)
plot(beta.den, trace=FALSE, density=TRUE, col='blue4', main='Beta')
lines(x, y, type='l', col='red4')
x = seq(0,3.1,by=0.001)
y = dexp(x, rate=1)
plot(u.den, trace=FALSE, density=TRUE, col='blue4', main='u')
lines(x, y, type='l', col='red4')
x = seq(0,1,by=0.001)
y = dgamma(x, shape=0.1, rate=0.1)
plot(sigma2.den, trace=FALSE, density=TRUE, col='blue4', main='Sigma2')
lines(x, y, type='l', col='red4')
y = dgamma(x, shape=0.1, rate=0.1)
plot(ita2.den, trace=FALSE, density=TRUE, col='blue4', main='Ita2')
lines(x, y, type='l', col='red4')
```

```{r 1e}
model1 = "model{
  x.0  ~ dnorm(log(2500), 1)
  x[1] ~ dnorm(beta * x.0 + u, inv.sigma02)
  y[1] ~ dnorm(x[1], inv.ita02)
  
  for (t in 2:n){
     mu[t] = beta*x[t-1] + u
     x[t] ~ dnorm(mu[t], inv.sigma02)
     y[t] ~ dnorm(x[t], inv.ita02)
  } 
  
  beta ~ dunif(beta.start,beta.end)
  u ~ dexp(u.shape)
  inv.sigma02 ~ dgamma(sigma.shape,sigma.rate)
  inv.ita02 ~ dgamma(ita.shape,ita.rate)
  sigma2 = 1/inv.sigma02
  ita2 = 1/inv.ita02
}"

beta.start <- -1
beta.end <- 2
u.shape <- 3
sigma.shape <- 1/0.1
sigma.rate <- 1/0.1
ita.shape <- 1/0.1
ita.rate <- 1/0.1

jm1 = jags.model(textConnection(model1),
                 data=list(n=n,
                           y=log(graywhales[,2]),
                           beta.start=0,
                           beta.end=1,
                           u.shape=1,
                           sigma.shape=0.1,
                           sigma.rate=0.1,
                           ita.shape=0.1,
                           ita.rate=0.1),
                 n.chains=3)
update(jm1,
       burn.in,
       progress.bar='none')
res1 = coda.samples(jm1,
                   variable.names=coef,
                   n.iter=5e3,
                   thin=500)

summary(res1)
summary(res)
gelman.diag(res1)
round(effectiveSize(res1),2)
acf(res1[[1]][,"beta"])
acf(res1[[1]][,"u"])
acf(res1[[1]][,"sigma2"])
acf(res1[[1]][,"ita2"])
```

```{r 1f}
p.years <- as.matrix(cbind(seq(1998,2050,by=1), rep(NA,53)),ncol=2,byrow=FALSE)
graywhales.p <- rbind(graywhales, p.years)
n.p=dim(graywhales.p)[1]
coef.p = c('x')

jm.p = jags.model(textConnection(model0), data=list(n=n.p, y=log(graywhales.p[,2])), n.chains=3)
update(jm.p, burn.in, progress.bar='none')
res.p = coda.samples(jm.p, variable.names=coef.p, n.iter=5e3, thin=500)
summary(res.p)

length(summary(res.p)[[1]][,1])

plot(graywhales.p[,1], summary(res.p)[[1]][,1],
     ylab='Log population',
     xlab='Years',
     type='l',
     col='blue4',
     ylim=c(7.9,12.5))
lines(graywhales.p[,1], summary(res.p)[[2]][,1],
      lty=2,
      col='pink',
      lwd=2)
lines(graywhales.p[,1], summary(res.p)[[2]][,5],
      lty=2,
      col='pink',
      lwd=2)
legend('topleft', legend=c("log-population", "95% symetric CI"),
       col=c("blue4", "pink"),
       lty=c(1,2,2),
       cex=0.8)

# probability calculation pending
```

```{r 1g}
#predictive checks
#replicated data
res.mat=as.matrix(res)
res.mat
beta=res.mat[,1]; sigma2=res.mat[,3]; u=res.mat[,4]
x=log(graywhales[,2])

niterf=nrow(res.mat)
yrep=matrix(0,nrow=n,ncol=niterf)
for(l in 1:niterf){
  for(i in 1:n){
    yrep[i,l]=rnorm(1,beta[l]*x[i]+u[l],sigma2[l])  
  }  
}
dim(yrep)

#statistics of interest in this case (and different from the ones included in the model)
yrepmin=apply(yrep,2,min, na.rm = TRUE)
yrepmax=apply(yrep,2,max, na.rm = TRUE)
yrepmedian=apply(yrep,2,median, na.rm = TRUE)
#Predictive checks using replicated data - minimum
hist(yrepmin,col="gray40", xlim=c(7.9,8.3))
abline(v=min(x, na.rm=TRUE),col="red",lwd=2)
hist(yrepmax,col="gray40")
abline(v=max(x, na.rm=TRUE),col="red",lwd=2)
hist(yrepmedian,col="gray40")
abline(v=median(x, na.rm=TRUE),col="red",lwd=2)
```

```{r 2a}
house.or <- read.csv(file = 'Real_estate.csv')
house <- house.or
# head(house)
temp <- house[c(1,8)]
house <- as.data.frame(scale(house[c(-1,-8)]))
house <- cbind(temp[1], house)
house.c <- cbind(house, temp[2])
house.c

# # manually centering the data matrix
# house2 <- read.csv(file = 'Real_estate.csv')
# n = nrow(house2)
# ones = rep(1, n)
# H = diag(n) - (1/n) * (ones %*% t(ones))
# 
# m = ncol(house2)
# ones.0 = rep(1, m)
# H.0 = diag(m) - 1/m * (ones.0 %*% t(ones.0))
# house2 <- as.data.frame(H %*% as.matrix(house2) %*% H.0)
# 
# house2

lin.mod0 <- lm(log(house.c$Y.house.price.of.unit.area) ~ 
                house.c$X1.transaction.date +
                house.c$X2.house.age + 
                house.c$X3.distance.to.the.nearest.MRT.station +
                house.c$X4.number.of.convenience.stores + 
                house.c$X5.latitude + house.c$X6.longitude)

lin.mod0$coefficients
mse.mod0 <- sqrt(sum(lin.mod0$residuals^2))
mse.mod0
summary(lin.mod0)
```

```{r 2b}
house <- read.csv(file = 'Real_estate.csv')
# head(house)
temp <- house[c(1,8)]
house <- as.data.frame(scale(house[c(-1,-8)]))
house <- cbind(temp[1], house, temp[2])
beta.prec <- 1/1e6

house.c

x1 <- house.c$X1.transaction.date
x2 <- house.c$X2.house.age
x3 <- house.c$X3.distance.to.the.nearest.MRT.station
x4 <- house.c$X4.number.of.convenience.stores
x5 <- house.c$X5.latitude
x6 <- house.c$X6.longitude
y  <- log(house.c$Y.house.price.of.unit.area)

data <- data.frame(y,x1,x2,x3,x4,x5,x6)
n <- nrow(data)
prec.prior <- list(prec=list(prior = "loggamma", param = c(0.1, 0.1)))
prior.beta <- list(mean.intercept = 0, prec.intercept = beta.prec,
                    mean = 0, prec = beta.prec)

lin.mod1 <- inla(y ~ x1 + x2 + x3 + x4 + x5 + x6,
            data=data,
            control.family=list(hyper=prec.prior),
            control.fixed=prior.beta,
            control.compute=list(cpo=TRUE, dic=TRUE))

summary(lin.mod1)

plot(lin.mod1$marginals.fixed$`(Intercept)`, type="l",xlab="beta0",ylab="Density",main='Posterior density of beta0')
plot(lin.mod1$marginals.fixed$x1,            type="l",xlab="beta1",ylab="Density",main='Posterior density of beta1')
plot(lin.mod1$marginals.fixed$x2,            type="l",xlab="beta2",ylab="Density",main='Posterior density of beta2')
plot(lin.mod1$marginals.fixed$x3,            type="l",xlab="beta3",ylab="Density",main='Posterior density of beta3')
plot(lin.mod1$marginals.fixed$x4,            type="l",xlab="beta4",ylab="Density",main='Posterior density of beta4')
plot(lin.mod1$marginals.fixed$x5,            type="l",xlab="beta5",ylab="Density",main='Posterior density of beta5')
plot(lin.mod1$marginals.fixed$x6,            type="l",xlab="beta6",ylab="Density",main='Posterior density of beta6')

cat("NSLCPO of model 1:",-sum(log(lin.mod1$cpo$cpo)),"\n")

res1 <- lin.mod1$summary.fitted.values$mean - y
sd.mean.res <- sd(res1)
sd.mean.res

# marginal.tau=lin.mod1$marginals.hyperpar[[1]]
# marginal.sigma2 <- inla.tmarginal(function(tau) tau^(-1), marginal.tau)
# plot(marginal.sigma2, type='l',
#      xlab="x",
#      ylab="Density",
#      main="Posterior density of sigma2")
```

```{r 2c}
n.post <- 1e2
lin.mod1I <- inla(y ~ x1 + x2 + x3 + x4 + x5 + x6,
            data=data,
            control.family=list(hyper=prec.prior),
            control.fixed=prior.beta,
            control.compute=list(config=TRUE),
            control.predictor = list(compute = TRUE))

lin.mod1L.post <- inla.posterior.sample(n.post, lin.mod1I)

fittedvalues <- inla.posterior.sample.eval(function(...) {Predictor}, lin.mod1L.post)
sigma <- 1/sqrt(inla.posterior.sample.eval(function(...) {theta}, lin.mod1L.post))
ymx <- as.matrix(y)%*%matrix(1,nrow=1,ncol=n.post)
x <- cbind(rep(1,n),x1,x2,x3,x4,x5,x6)
H <- x%*%solve((t(x)%*%x))%*%t(x)

y.log <- log(data$y)
ymx <- as.matrix(y.log)%*%matrix(1,nrow=1,ncol=n.post)

studentised.res <- y - fittedvalues

for(l in 1:n.post){
  studentised.res[,l]=studentised.res[,l]/sigma[l];
}
for(i in 1:n){
  studentised.res[i,]=studentised.res[i,]/sqrt(1-H[i,i]);
}
#posterior mean of studentised residuals
studentised.res.m=numeric(n)
for(i in 1:n){
  studentised.res[i]=mean(studentised.res[i,])  
}

#Plot of posterior mean studentised residual versus observation number.
par(mfrow=c(1,2))
qqnorm(studentised.res.m, lwd=2,xlab="Index", ylab="Bayesian studentised residual")
plot(seq_along(studentised.res.m), rowMeans(fittedvalues), xlab="Fitted Values", ylab="Bayesian studentised residual", main="Residuals against fitted vlues")

```

```{r 2d}
#Setting the priors for Student's t distribution
prior.t.rob <- list(prec=list(prior = "loggamma", param = c(0.1, 0.1)), dof = list(prior = "loggamma",param = c(1,1)) ) 
prior.beta.rob <- list(mean.intercept = 0, prec.intercept = 1/1e6,
                    mean = 0, prec = 1/1e6)

data <- data.frame(data)
lin.mod1.rob <- inla(y ~ x1 + x2 + x3 + x4 + x5 + x6,
                     family="T",
                     data=data,
                     control.family=list(hyper=prior.t.rob),
                     control.fixed=prior.beta.rob,
                     control.compute=list(cpo=TRUE, dic=TRUE))

summary(lin.mod1.rob)
lin.mod1.rob$marginals.hyper$`degrees of freedom for student-t`

plot(lin.mod1.rob$marginals.hyper$`degrees of freedom for student-t`,
     type ="l",
     xlab="x",
     ylab="Density",
     main='Posterior density of dof parameter nu for robust regression',
     xlim=c(1,10),
     ylim=c(0,1.1))

cat("NSLCPO of robust model:",-sum(log(lin.mod1.rob$cpo$cpo)),"\n")
cat("DIC of robust model:",lin.mod1.rob$dic$dic,"\n")

res2 <- lin.mod1.rob$summary.fitted.values$mean - y
sd.mean.res <- sd(res2)
sd.mean.res
```

```{r 2e}
house.fac <- house.or
house.fac.x4 <- as.factor(house.fac$X4.number.of.convenience.stores)
data <- data.frame(y,x1,x2,x3,house.fac.x4,x5,x6)

n <- nrow(data)
prec.prior <- list(prec=list(prior = "loggamma", param = c(0.1, 0.1)))
prior.beta <- list(mean.intercept = 0, prec.intercept = beta.prec,
                    mean = 0, prec = beta.prec)

lin.mod1.fac <- inla(y ~ x1 + x2 + x3 + house.fac.x4 + x5 + x6,
            data=data,
            control.family=list(hyper=prec.prior),
            control.fixed=prior.beta,
            control.compute=list(cpo=TRUE, dic=TRUE))

prior.t.rob <- list(prec=list(prior = "loggamma", param = c(0.1, 0.1)), dof = list(prior = "loggamma",param = c(1,1)) ) 
prior.beta.rob <- list(mean.intercept = 0, prec.intercept = 1/1e6,
                    mean = 0, prec = 1/1e6)

lin.mod1.rob.fac <- inla(y ~ x1 + x2 + x3 + house.fac.x4 + x5 + x6,
                         family="T",
                         data=data,
                         control.family=list(hyper=prior.t.rob),
                         control.fixed=prior.beta.rob,
                         control.compute=list(cpo=TRUE, dic=TRUE))

summary(lin.mod1.fac)
summary(lin.mod1.rob.fac)

cat("NSLCPO of factor simple model:",-sum(log(lin.mod1.fac$cpo$cpo)),"\n")
cat("NSLCPO of factor robust model:",-sum(log(lin.mod1.rob.fac$cpo$cpo)),"\n")

res.frac1 <- lin.mod1.fac$summary.fitted.values$mean - y
sd.mean.res.frac1 <- sd(res.frac1)
res.frac2 <- lin.mod1.rob.fac$summary.fitted.values$mean - y
sd.mean.res.frac2 <- sd(res.frac2)

sd.mean.res.frac1
sd.mean.res.frac2
```

```{r 2f}
prior.t.rob <- list(prec=list(prior = "loggamma", param = c(0.1, 0.1)), dof = list(prior = "loggamma",param = c(1,1)) ) 
prior.beta.rob <- list(mean.intercept = 0, prec.intercept = 1/1e6,
                    mean = 0, prec = 1/1e6)
data <- data.frame(y,x1,x2,x3,house.fac.x4,x5,x6)

lin.mod.final <- inla(y ~ x1 + x2 + x3 + house.fac.x4 + x5 + x6,
                      family="T",
                      data=data,
                      control.family=list(hyper=prior.t.rob),
                      control.fixed=prior.beta.rob,
                      control.compute=list(cpo=TRUE, dic=TRUE))

# summary(lin.mod.final)

cat("NSLCPO of factor simple model:",-sum(log(lin.mod.final$cpo$cpo)),"\n")
cat("DIC of robust model:",lin.mod.final$dic$dic,"\n")

res.frac1 <- lin.mod.final$summary.fitted.values$mean - y
sd.mean.res.frac1 <- sd(res.frac1)
```

```{r 2g}

```