---
title: "Assignment2"
author: "Ted Ladas - s2124289"
date: "30/03/2021"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
library(rjags)
library(INLA)
library(dplyr)
library(data.table)
library(ggplot2)
library(ggcorrplot)
library(gridExtra)
```

```{r 1.a(i)}
load(file='./earthScot.RData')
earthQ <- data.table(earthQ)

# EDA
numcols <- sapply(earthQ, is.numeric) 
cor.earthQ <- cor(earthQ, use="pairwise.complete")
ggcorrplot(cor.earthQ,
           hc.order=TRUE,
           type="lower",
           lab=TRUE)

plot <- earthQ %>% 
  filter(!is.na(`nrUK>4.5`))

plot %>%
  ggplot(aes(dist, eartScot,
             size=MLrUK,
             color=`nrUK>4.5`)) +
  geom_point() +
  geom_smooth(method="glm",
              formula='y~x',
              se=FALSE)

plot %>%
  ggplot(aes(decade, eartScot,
             size=MLrUK,
             color=`nrUK>4.5`)) +
  geom_point() +
  geom_smooth(method="glm",
              formula='y~x',
              se=FALSE)

plot %>%
  ggplot(., aes(eartrUK, eartScot,
                size=MLrUK,
                color=`nrUK>4.5`)) +
  geom_point() +
  geom_smooth(method="glm",
              formula='y~x',
              se=FALSE)

```

```{r 1.a(ii)}

a1 <- glm(eartScot~eartrUK, data=earthQ, family=poisson(link = "log"))
summary(a1)

earthQ %>% 
  ggplot(., aes(eartrUK, eartScot)) +
  geom_point(size=3) +
  geom_smooth(method="glm",
              formula='y~x',
              method.args=list(family=poisson(link="log")),
              se=T,
              aes(color="red4"), linetype="dashed") +
  labs(title = "Poisson Regression",
       subtitle = NULL,
       caption = NULL,
       tag = NULL,
       #x = NULL,
       #y = NULL,
       colour = "Regression") +
  theme_minimal()

# coefficients of regression after unlinking
a1.coef.unlinked <- a1 %>% coef() %>% exp()
# earthquakes during 70s and 80s
a1.fited <- a1 %>% predict(., type="response")
earthquakes.70.80 <- NULL
earthquakes.70.80 <- cbind(c(1970,1980),a1.fited[7:8])

a1.coef.unlinked
earthquakes.70.80


earthQ %>%
  dplyr::select(eartScot,eartrUK, decade) %>%
  mutate(eartScot.pred.a1 = a1.fited) %>%
  ggplot() +
  geom_point(aes(x=decade, y=eartScot, color='Actual')) +
  geom_line(aes(x=decade, y=eartScot, color='Actual')) +
  geom_point(aes(x=decade, y=eartScot.pred.a1, color='a1 Prediction')) +
  geom_line(aes(x=decade, y=eartScot.pred.a1, color='a1 Prediction')) +
  labs(title="GLM fit predictions",
       color=NULL) +
  theme_minimal()

```

```{r 1.b(model.s)}
model.s <- "model{
  # Hyperparameters
  a.0 <- a        
  b.0 <- b

  # prior
  lambda ~ dgamma(a.0,b.0)

 #Likelihood
  for(i in 1:n) {
      mu[i]  <- lambda*eartrUK[i]
      eartScot[i] ~ dpois(mu[i])
    } 
  }"
inits <- list(list(lambda=10^0),
              list(lambda=10^1),
              list(lambda=10^2),
              list(lambda=10^3),
              list(lambda=10^4))
```

```{r 1.b(i)}
b1.data <- list(n=length(earthQ$eartrUK),
               eartScot=earthQ$eartScot,
               eartrUK =earthQ$eartrUK,
               a=0.01,
               b=0.01)

fit.b1 <- jags.model(file=textConnection(model.s),
                     data=b1.data, 
                     inits=inits,
                     n.chains=5)
update(fit.b1, n.iter=7000)
results.b1 <- coda.samples(fit.b1,
                           variable.names=c("lambda"),
                           n.iter=1e4)

# convergence and summary statistics for b1
plot(results.b1)
summary(results.b1)
gelman.diag(results.b1)
gelman.plot(results.b1)
round(effectiveSize(results.b1),2)
acf(results.b1[[1]][,"lambda"])
```

```{r 1.b(ii)}
b2.data <- list(n=length(earthQ$eartrUK),
               eartScot=earthQ$eartScot,
               eartrUK =earthQ$eartrUK,
               a=16,
               b=20)

fit.b2 <- jags.model(file=textConnection(model.s),
                     data=b2.data,
                     inits=inits,
                     n.chains=5)
update(fit.b2, n.iter=7000)
results.b2 <- coda.samples(fit.b2,
                           variable.names=c("lambda"),
                           n.iter=1e4)


# convergence and summary statistics for b2
plot(results.b2)
summary(results.b2)
gelman.diag(results.b2)
gelman.plot(results.b2)
round(effectiveSize(results.b2),2)
acf(results.b2[[1]][,"lambda"])
```

```{r 1.b(model.h)}
model.h <- "model{
 # Deterministic
  sigma2 = 1/tau

 # Hyperpriors
  a.0 ~ dlnorm(log(a), tau)
  b.0 ~ dlnorm(log(b), tau)
  
 # Prior
  lambda ~ dgamma(a.0,b.0)

 # Likelihood
  for(i in 1:n) {
      mu[i]  <- lambda*eartrUK[i]
      eartScot[i] ~ dpois(mu[i])
    } 
  }"
inits <- list(list(lambda=10^0),
              list(lambda=10^1),
              list(lambda=10^2),
              list(lambda=10^3),
              list(lambda=10^4))
```

```{r 1.b(iii)}
b3.data <- list(n=length(earthQ$eartrUK),
               eartScot=earthQ$eartScot,
               eartrUK =earthQ$eartrUK,
               a=2,
               b=4,
               tau=log(1.64))

fit.b3 <- jags.model(file=textConnection(model.h),
                     data=b3.data, 
                     inits=inits,
                     n.chains=5)
update(fit.b3, n.iter=6000)
results.b3 <- coda.samples(fit.b3,
                           variable.names=c("lambda", "a.0", "b.0"),
                           n.iter=1e5,
                           thin=50)

# convergence and summary statistics for b3
plot(results.b3)
summary(results.b3)
gelman.diag(results.b3)
gelman.plot(results.b3)
round(effectiveSize(results.b3),2)
acf(results.b3[[1]][,"lambda"])
acf(results.b3[[1]][,"a.0"])
acf(results.b3[[1]][,"b.0"])
```

```{r 1.c(model.c1)}
model.c1 <- "model{
 # prior
  beta0 ~ dnorm(0,1/5)
  beta1 ~ dnorm(0,1/5)

 # Likelihood
  for(i in 1:n) {
      log(mu[i]) <- beta0+beta1*(dist[i]-mean(dist[]))
      eartScot[i] ~ dpois(mu[i])
    } 
  }"
```

```{r 1.c}
c1.data <- list(n=length(earthQ$eartrUK),
               eartScot=earthQ$eartScot,
               dist =earthQ$dist)

fit.c1 <- jags.model(file=textConnection(model.c1),
                     data=c1.data, 
                     inits=inits,
                     n.chains=5)
update(fit.c1, n.iter=6000)
results.c1 <- coda.samples(fit.c1,
                           variable.names=c("beta0", "beta1"),
                           n.iter=1e4,
                           thin=5)

# convergence and summary statistics for c1
plot(results.c1)
summary(results.c1)
gelman.diag(results.c1)
gelman.plot(results.c1)
round(effectiveSize(results.c1),2)
acf(results.c1[[1]][,"beta0"])
acf(results.c1[[1]][,"beta1"])
```

```{r 1.d(model.d1)}
model.d1 <- "model{
 # Likelihood
  for(i in 1:n) {
      delta[i] ~ dnorm(0,tau.delta)
      log(mu[i]) <- beta0+beta1*(dist[i]-mean(dist[])) + delta[i]
      eartScot[i] ~ dpois(mu[i])
  } 
    
 # prior
  beta0 ~ dnorm(0,1/5)
  beta1 ~ dnorm(0,1/5)
  tau.delta <- pow(sigma.delta, -2)
  sigma.delta ~ dunif(0,5)
  }"
```

```{r 1.d}
d1.data <- list(n=length(earthQ$eartrUK),
               eartScot=earthQ$eartScot,
               dist=earthQ$dist)

fit.d1 <- jags.model(file=textConnection(model.d1),
                     data=d1.data, 
                     inits=inits,
                     n.chains=5)
update(fit.d1, n.iter=6000)
results.d1 <- coda.samples(fit.d1,
                           variable.names=c("beta0", "beta1", "sigma.delta"),
                           n.iter=1e5,
                           thin=100)

# convergence and summary statistics for c1
plot(results.d1)
summary(results.d1)
gelman.diag(results.d1)
gelman.plot(results.d1)
round(effectiveSize(results.d1),2)
acf(results.d1[[1]][,"beta0"])
acf(results.d1[[1]][,"beta1"])
acf(results.d1[[1]][,"sigma.delta"])
```



```{r 1.e(model.e1)}
model.e1 <- "model{
 # prior
  beta0 ~ dnorm(0,1/5)
  beta1 ~ dnorm(0,1/5)

 # Likelihood
  for(i in 1:n) {
      log(mu[i]) <- beta0+beta1*(nrUK[i]-mean(nrUK[]))
      eartScot[i] ~ dpois(mu[i])
    } 
  }"
```


```{r 1.e imputation}



```


```{r 1.e}
e1.data <- list(n=length(earthQ$eartrUK),
               eartScot=earthQ$eartScot,
               nrUK =earthQ$`nrUK>4.5`)

fit.e1 <- jags.model(file=textConnection(model.e1),
                     data=e1.data, 
                     inits=inits,
                     n.chains=5)
update(fit.e1, n.iter=6000)
results.e1 <- coda.samples(fit.e1,
                           variable.names=c("beta0", "beta1"),
                           n.iter=1e4,
                           thin=5)

# convergence and summary statistics for e1
plot(results.e1)
summary(results.e1)
gelman.diag(results.e1)
gelman.plot(results.e1)
round(effectiveSize(results.e1),2)
acf(results.e1[[1]][,"beta0"])
acf(results.e1[[1]][,"beta1"])
```



```{r 2.a}

```

```{r 2.b}

```

```{r 2.c}

```

```{r 2.d}

```

```{r 2.e}

```
